<?xml version="1.0" encoding="utf-8"?><Database Name="Site" Class="BasedeDadosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-EN9BC5I\SQLEXPRESS;Initial Catalog=Site;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SiteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.cadastro" Member="cadastro">
    <Type Name="cadastro">
      <Column Name="cpf" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telefone" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="endereco" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="logradouro" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="complemento" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="bairro" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cidade" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_end" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>